Fix NPE coming from null in the buffer
java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "contents" is null
	at org.eclipse.jdt.internal.ui.fix.RedundantSemicolonsCleanUp.findTrailingSemicolons(RedundantSemicolonsCleanUp.java:202)
	at org.eclipse.jdt.internal.ui.fix.RedundantSemicolonsCleanUp.searchNode(RedundantSemicolonsCleanUp.java:117)
	at org.eclipse.jdt.internal.ui.fix.RedundantSemicolonsCleanUp$1.visit(RedundantSemicolonsCleanUp.java:140)
	at org.eclipse.jdt.core.dom.PackageDeclaration.accept0(PackageDeclaration.java:208)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3302)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:256)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.internal.ui.fix.RedundantSemicolonsCleanUp.createFix(RedundantSemicolonsCleanUp.java:137)
	at org.eclipse.jdt.internal.ui.fix.AbstractMultiFix.createFix(AbstractMultiFix.java:49)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:772)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.calculateSolutions(CleanUpRefactoring.java:301)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.acceptAST(CleanUpRefactoring.java:279)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1008)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:692)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:954)
	at org.eclipse.jdt.internal.corext.dom.ASTBatchParser.createASTs(ASTBatchParser.java:82)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpFixpointIterator.next(CleanUpRefactoring.java:399)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.cleanUpProject(CleanUpRefactoring.java:682)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.checkFinalConditions(CleanUpRefactoring.java:642)